apiVersion: v1
kind: Service
metadata:
  name: chris-jenkins-service
spec:
  type: NodePort
  selector:
    app: chris-jenkins
  ports:
    - port: 8080  		# Service port
      targetPort: 8080 	# Pod port
      nodePort: 31011  	# Exposed on the node
